# Generated by Django 5.2.13 on 2026-04-28 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video_file', models.FileField(help_text='Format MP4 recommandé, max 100MB', upload_to='showcase_videos/', verbose_name='Vidéo')),
                ('thumbnail', models.ImageField(blank=True, help_text='Image de couverture (optionnel)', null=True, upload_to='showcase_thumbnails/', verbose_name='Miniature')),
                ('category', models.CharField(choices=[('promo', 'Promotion'), ('tutorial', 'Tutoriel'), ('announcement', 'Annonce'), ('testimonial', 'Témoignage'), ('feature', 'Fonctionnalité')], default='promo', max_length=20, verbose_name='Catégorie')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('auto_play', models.BooleanField(default=True, verbose_name='Jouer automatiquement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase_videos', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Annonce Vidéo',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
