# Generated by Django 5.2.13 on 2026-04-29 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la salle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('google_meet_link', models.CharField(blank=True, max_length=500, verbose_name='Lien Google Meet')),
                ('access_code', models.CharField(blank=True, max_length=20, verbose_name="Code d'accès")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_public', models.BooleanField(default=True, verbose_name='Publique')),
                ('max_participants', models.IntegerField(default=50, verbose_name='Participants max')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Débutée le')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminée le')),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('live', 'En direct'), ('ended', 'Terminée')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
            ],
            options={
                'verbose_name': 'Salle de réunion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_system_message', models.BooleanField(default=False, verbose_name='Message système')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='videoconf.meetingroom', verbose_name='Salle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Message de salle',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('host', 'Hôte'), ('moderator', 'Modérateur'), ('participant', 'Participant')], default='participant', max_length=20, verbose_name='Rôle')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='A quitté le')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Muet')),
                ('is_camera_on', models.BooleanField(default=True, verbose_name='Caméra active')),
                ('status', models.CharField(choices=[('waiting', "Salle d'attente"), ('in_room', 'Dans la salle'), ('left', 'A quitté')], default='in_room', max_length=20, verbose_name='Statut')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='videoconf.meetingroom', verbose_name='Salle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Participant',
                'ordering': ['joined_at'],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
