# Generated by Django 5.2.13 on 2026-04-28 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0001_initial'),
        ('compositions', '0002_initial'),
        ('qcm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='composition_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins', to='compositions.compositionsession'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='qcm_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins', to='qcm.qcmexam'),
        ),
    ]
