# Generated by Django 5.2.13 on 2026-04-27 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('icone', models.CharField(default='🏆', max_length=10, verbose_name='icône emoji')),
                ('icone_svg', models.URLField(blank=True, null=True, verbose_name='URL SVG icon')),
                ('categorie', models.CharField(choices=[('academique', 'Académique'), ('participation', 'Participation'), ('excellence', 'Excellence'), ('progression', 'Progression'), ('social', 'Social & Communautaire'), ('special', 'Spécial & Événementiel'), ('competition', 'Compétition'), ('mentorat', 'Mentorat & Aide')], default='academique', max_length=20, verbose_name='catégorie')),
                ('points_valeur', models.PositiveIntegerField(default=50, verbose_name='valeur en XP')),
                ('condition_obtention', models.JSONField(default=dict, help_text="Ex: {'compositions': 10, 'moyenne_min': 15}", verbose_name='conditions')),
                ('est_actif', models.BooleanField(default=True, verbose_name='actif')),
                ('visible_public', models.BooleanField(default=True, verbose_name='visible publiquement')),
                ('is_achievable', models.BooleanField(default=True, verbose_name='atteignable')),
                ('rarete', models.CharField(choices=[('commun', 'Commun 🟢'), ('rare', 'Rare 🔵'), ('epique', 'Épique 🟣'), ('legendaire', 'Légendaire 🟠'), ('mythique', 'Mythique ⭐')], default='commun', max_length=20, verbose_name='rareté')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name='ordre affichage')),
                ('nb_attributions', models.PositiveIntegerField(default=0)),
                ('dernier_attribution', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'badge',
                'verbose_name_plural': 'badges',
                'ordering': ['ordre_affichage', '-points_valeur', 'rarete'],
                'indexes': [
                    models.Index(fields=['categorie', 'est_actif'], name='gamificatio_categorie_2a6c4f_idx'),
                    models.Index(fields=['rarete'], name='gamificatio_rarete_8f3d12_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('categorie', models.CharField(default='Général', max_length=100, verbose_name='catégorie')),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=20, verbose_name='difficulté')),
                ('date_debut', models.DateTimeField(verbose_name='début')),
                ('date_fin', models.DateTimeField(verbose_name='fin')),
                ('duree_minutes', models.PositiveIntegerField(default=60, verbose_name='durée minutes')),
                ('prix_total', models.PositiveIntegerField(default=1000, verbose_name='prix total XP')),
                ('places_premieres', models.PositiveIntegerField(default=1, verbose_name='premiers prix')),
                ('status', models.CharField(choices=[('preparation', 'Préparation'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='preparation', max_length=20, verbose_name='status')),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_debut'],
                'indexes': [
                    models.Index(fields=['status', 'date_debut'], name='gamificatio_status_1a2b3c_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='CommunityContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_contribution', models.CharField(choices=[('reponse_aide', 'Réponse aide élève'), ('partage_ressource', 'Partage ressource'), ('creation_contenu', 'Création contenu'), ('moderation', 'Modération'), ('organisation_event', 'Organisation événement')], max_length=20, verbose_name='type')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('xp_recompense', models.PositiveIntegerField(default=25)),
                ('est_recompensee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode', models.CharField(choices=[('jour', 'Journalier'), ('semaine', 'Hebdomadaire'), ('mois', 'Mensuel'), ('annee', 'Annuel'), ('all_time', 'Tous les temps')], default='all_time', max_length=20, verbose_name='période')),
                ('date_periode', models.DateField(verbose_name='date période référence')),
                ('rang_mondial', models.PositiveIntegerField(default=99999, verbose_name='rang mondial')),
                ('rang_national', models.PositiveIntegerField(default=99999, verbose_name='rang national')),
                ('rang_classe', models.PositiveIntegerField(default=99999, verbose_name='rang dans classe')),
                ('rang_institution', models.PositiveIntegerField(default=99999, verbose_name='rang institution')),
                ('score_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='score total (XP+achievements)')),
                ('points_xp', models.PositiveIntegerField(default=0, verbose_name='points XP totaux')),
                ('niveau', models.PositiveIntegerField(default=1, verbose_name='niveau actuel')),
                ('nb_compositions', models.PositiveIntegerField(default=0, verbose_name='compositions passées')),
                ('nb_excellentes', models.PositiveIntegerField(default=0, verbose_name='notes excellentes (≥16/20)')),
                ('moyenne_generale', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='moyenne générale')),
                ('streak_jours', models.PositiveIntegerField(default=0, verbose_name='série jours actifs')),
                ('badges_obtenus', models.PositiveIntegerField(default=0, verbose_name='nombre de badges')),
                ('interventions_communaute', models.PositiveIntegerField(default=0, verbose_name='contributions communautaires')),
                ('pays', models.CharField(default='Non renseigné', max_length=100, verbose_name='pays')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='ville')),
                ('classement_actuel', models.BooleanField(default=False, verbose_name='dans top 10%')),
                ('progression_semaine', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='progression cette semaine %')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'classement',
                'verbose_name_plural': 'classements',
                'unique_together': {('user', 'periode', 'date_periode')},
                'indexes': [
                    models.Index(fields=['rang_mondial'], name='gamificatio_rang_mo_4d5e6f_idx'),
                    models.Index(fields=['rang_national'], name='gamificatio_rang_na_7g8h9i_idx'),
                    models.Index(fields=['score_total', 'date_periode'], name='gamificatio_score_t_0j1k2l_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='StreakRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='série actuelle jours')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='plus longue série record')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='dernière activité')),
                ('last_check_date', models.DateField(blank=True, null=True, verbose_name='dernier check')),
                ('streak_bonus_level', models.PositiveIntegerField(default=0, verbose_name='niveau bonus streak')),
                ('streak_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='multiplicateur XP')),
                ('days_active_this_month', models.PositiveIntegerField(default=0, verbose_name='jours actifs ce mois')),
                ('total_logins', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'série activité',
                'verbose_name_plural': 'séries activité',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obtenu_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='obtenu le')),
                ('est_nouveau', models.BooleanField(default=True, verbose_name='nouveau (non lu)')),
                ('performances', models.JSONField(blank=True, default=dict, help_text="Stats personnalisées ex: {'score_moyen': 16.5, 'tentatives': 3}", verbose_name='performances sur ce badge')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'badge utilisateur',
                'verbose_name_plural': 'badges utilisateur',
                'unique_together': {('user', 'badge')},
                'ordering': ['-obtenu_at'],
                'indexes': [
                    models.Index(fields=['user', 'est_nouveau'], name='gamificatio_user_id_3m4n5o_idx'),
                    models.Index(fields=['obtenu_at'], name='gamificatio_obtenu__6p7q8r_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='XPAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('connexion', 'Connexion quotidienne'), ('composition_finie', 'Examen terminé'), ('note_excellente', 'Note ≥ 16/20'), ('badge_obtenu', 'Badge débloqué'), ('qcm_reussi', 'QCM réussi'), ('aide_partenaire', 'Aide donnée à pair'), ('contribution_forum', 'Post/forum créé'), ('streak_bonus', 'Bonus série'), ('competition_gagnee', 'Compétition remportée'), ('mentorat_heure', 'Heure de mentorat'), ('cours_termine', 'Cours complété'), ('participation_event', 'Événement participé')], max_length=50, verbose_name='type action')),
                ('points_gagnes', models.PositiveIntegerField(default=0, verbose_name='points XP gagnés')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'action XP',
                'verbose_name_plural': 'actions XP',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'created_at'], name='gamificatio_user_id_9s0t1u_idx'),
                    models.Index(fields=['action_type'], name='gamificatio_action__2v3w4x_idx'),
                ],
            },
        ),
    ]
