# Generated by Django 5.2.13 on 2026-04-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalleaderboard',
            options={'ordering': ['-score_total', '-rang_mondial'], 'verbose_name': 'classement', 'verbose_name_plural': 'classements'},
        ),
        migrations.RenameIndex(
            model_name='badge',
            new_name='gamificatio_categor_006bce_idx',
            old_name='gamificatio_categorie_2a6c4f_idx',
        ),
        migrations.RenameIndex(
            model_name='badge',
            new_name='gamificatio_rarete_667c08_idx',
            old_name='gamificatio_rarete_8f3d12_idx',
        ),
        migrations.RenameIndex(
            model_name='competition',
            new_name='gamificatio_status_052f6a_idx',
            old_name='gamificatio_status_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='globalleaderboard',
            new_name='gamificatio_rang_mo_891c1c_idx',
            old_name='gamificatio_rang_mo_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='globalleaderboard',
            new_name='gamificatio_rang_na_89e45d_idx',
            old_name='gamificatio_rang_na_7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='globalleaderboard',
            new_name='gamificatio_score_t_bd84e3_idx',
            old_name='gamificatio_score_t_0j1k2l_idx',
        ),
        migrations.RenameIndex(
            model_name='userbadge',
            new_name='gamificatio_user_id_ea85bd_idx',
            old_name='gamificatio_user_id_3m4n5o_idx',
        ),
        migrations.RenameIndex(
            model_name='userbadge',
            new_name='gamificatio_obtenu__8f1fa0_idx',
            old_name='gamificatio_obtenu__6p7q8r_idx',
        ),
        migrations.RenameIndex(
            model_name='xpaction',
            new_name='gamificatio_user_id_499253_idx',
            old_name='gamificatio_user_id_9s0t1u_idx',
        ),
        migrations.RenameIndex(
            model_name='xpaction',
            new_name='gamificatio_action__09e4d5_idx',
            old_name='gamificatio_action__2v3w4x_idx',
        ),
    ]
